spring:
  application:
    name: eureka-server
  security:
    user:
      name: root
      password: 123456
server:
  port: 8761
eureka:
  client:
    service-url:
      defalutZone: http://root:123456@localhost:8761/eureka/
    fetch-registry: false # 服务发现
    register-with-eureka: false # 服务注册

